apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: ecommerce
data:
  TZ: "UTC"
  mysql.cnf: |
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    default-time-zone=+00:00
    max-connections=100
