apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ecommerce
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-password: ecommerce_pass
  mysql-user: ecommerce_user
  mysql-database: ecommerce
